### ISSUE TITLE
Nothing happens when trying to search via Chrome omnibox

### ISSUE THREAD

**Issue by tschaena** [anth0d/chrome-confluence-search#8]
I installed the extension for searching on my private Confluence cloud instance. Searching works well via the normal search window (triggered via the extension bar icon) but doesn't work via the Chrome omnibox. When I enter a search term and press enter in the Chrome omnibox, nothing happens. 
![image](https://user-images.githubusercontent.com/6318623/130685286-3c3060c1-5136-4c78-b97a-d20570a8d359.png)
There are no search results, no error message, etc. The only thing happening is that the search bar is reset. 
![image](https://user-images.githubusercontent.com/6318623/130685486-004385aa-05a8-46b3-ad3e-30273bad8504.png)

Is this a known issue?

**Comment by anth0d** [comment]
Hey @tschaena this hasn't been reported before, thank you for opening this issue! Sorry to hear this is not working for you, I will take a look!

**Comment by anth0d** [comment]
This should be fixed in the upcoming `1.1.14` version. Will close this when that's been published.

**Comment by anth0d** [comment]
Okay, visit [chrome://extensions](chrome://extensions) and click **Update** and you should see `1.1.4`. 

Thanks for reporting, please let me know if this doesn't fix your issue.

**Comment by tschaena** [comment]
@anth0d II just checked it today with Chrome Version 93.0.4577.82. Unfortunately, it still doesn't work. I managed once that it did do something (no clue how) but now I am back with the same behavior. Also restarting Chrome does not work.

**Comment by anth0d** [comment]
Ah, I apologize, that's annoying. Initially I was able to reproduce the issue, and after my change it appeared to work consistently. Thanks for letting me know, I will look into this some more.

**Comment by anth0d** [comment]
Sorry for the delay, @tschaena could you open the dev tools (chrome://extensions/ contains a "Inspect" link to the extension's background page) and let me know if you see errors when using the omnibox shortcut?

**Comment by tschaena** [comment]
@anth0d After updating to 1.1.5, I don't get this issue anymore (with or without inspect window it works). No clue why that is. Should I run into the issue again, I will report it here.
